CREATE TABLE IF NOT EXISTS `sovex_garages` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(60) NOT NULL,
  `type` VARCHAR(20) NOT NULL DEFAULT 'public',
  `label` VARCHAR(80) NOT NULL,
  `coords` LONGTEXT NOT NULL,
  `spawn` LONGTEXT NOT NULL,
  `created_by` VARCHAR(64) NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uniq_name` (`name`)
);

ALTER TABLE sovex_garages
  ADD COLUMN IF NOT EXISTS `menu` LONGTEXT NULL,
  ADD COLUMN IF NOT EXISTS `store` LONGTEXT NULL;

ALTER TABLE sovex_garages
  MODIFY COLUMN coords LONGTEXT NULL;

ALTER TABLE sovex_garages
  ADD COLUMN IF NOT EXISTS access_type VARCHAR(20) NOT NULL DEFAULT 'public',
  ADD COLUMN IF NOT EXISTS access_data LONGTEXT NULL;

ALTER TABLE player_vehicles
  ADD COLUMN IF NOT EXISTS sovex_damage LONGTEXT NULL;
